from __future__ import annotations


AI_WEBSITES = [
    {
        "id": "chatgpt",
        "name": "ChatGPT",
        "provider": "openai",
        "website": "https://chatgpt.com/",
        "apiWebsite": "https://platform.openai.com/",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["chief", "code", "review", "summary", "translation"],
    },
    {
        "id": "claude",
        "name": "Claude",
        "provider": "claude",
        "website": "https://claude.ai/",
        "apiWebsite": "https://console.anthropic.com/",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["chief", "review", "summary", "translation"],
    },
    {
        "id": "gemini",
        "name": "Gemini",
        "provider": "gemini",
        "website": "https://gemini.google.com/",
        "apiWebsite": "https://aistudio.google.com/",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["chief", "code", "summary", "translation"],
    },
    {
        "id": "deepseek",
        "name": "DeepSeek",
        "provider": "deepseek",
        "website": "https://chat.deepseek.com/",
        "apiWebsite": "https://platform.deepseek.com/",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["code", "review", "summary"],
    },
    {
        "id": "qwen",
        "name": "Qwen",
        "provider": "qwen",
        "website": "https://chat.qwen.ai/",
        "apiWebsite": "https://dashscope.aliyun.com/",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["code", "summary", "translation"],
    },
    {
        "id": "kimi",
        "name": "Kimi",
        "provider": "kimi",
        "website": "https://www.kimi.com/",
        "apiWebsite": "https://platform.moonshot.cn/",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["summary", "review", "translation"],
    },
    {
        "id": "doubao",
        "name": "Doubao",
        "provider": "doubao",
        "website": "https://www.doubao.com/",
        "apiWebsite": "https://www.volcengine.com/product/ark",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["summary", "translation"],
    },
    {
        "id": "yuanbao",
        "name": "Yuanbao",
        "provider": "tencent",
        "website": "https://yuanbao.tencent.com/",
        "apiWebsite": "https://cloud.tencent.com/product/hunyuan",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["summary", "translation"],
    },
    {
        "id": "zhipu",
        "name": "Zhipu Qingyan",
        "provider": "zhipu",
        "website": "https://chatglm.cn/",
        "apiWebsite": "https://open.bigmodel.cn/",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["review", "summary", "translation"],
    },
    {
        "id": "ernie",
        "name": "ERNIE Bot",
        "provider": "baidu",
        "website": "https://yiyan.baidu.com/",
        "apiWebsite": "https://cloud.baidu.com/product/wenxinworkshop",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["summary", "translation"],
    },
    {
        "id": "spark",
        "name": "SparkDesk",
        "provider": "iflytek",
        "website": "https://xinghuo.xfyun.cn/",
        "apiWebsite": "https://www.xfyun.cn/solutions/xinghuoAPI",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["summary", "translation"],
    },
    {
        "id": "minimax",
        "name": "MiniMax",
        "provider": "minimax",
        "website": "https://www.minimaxi.com/",
        "apiWebsite": "https://platform.minimaxi.com/",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["summary", "translation"],
    },
    {
        "id": "stepfun",
        "name": "StepFun",
        "provider": "stepfun",
        "website": "https://www.stepfun.com/",
        "apiWebsite": "https://platform.stepfun.com/",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["summary", "review"],
    },
    {
        "id": "baichuan",
        "name": "Baichuan",
        "provider": "baichuan",
        "website": "https://www.baichuan-ai.com/",
        "apiWebsite": "https://platform.baichuan-ai.com/",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["summary", "translation"],
    },
    {
        "id": "grok",
        "name": "Grok",
        "provider": "xai",
        "website": "https://grok.com/",
        "apiWebsite": "https://x.ai/api",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["review", "summary"],
    },
    {
        "id": "perplexity",
        "name": "Perplexity",
        "provider": "perplexity",
        "website": "https://www.perplexity.ai/",
        "apiWebsite": "https://docs.perplexity.ai/",
        "freeTier": True,
        "loginRequired": False,
        "authMode": "optional_login",
        "roles": ["review", "summary"],
    },
    {
        "id": "poe",
        "name": "Poe",
        "provider": "poe",
        "website": "https://poe.com/",
        "apiWebsite": "",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["chief", "summary", "translation"],
    },
    {
        "id": "huggingchat",
        "name": "HuggingChat",
        "provider": "huggingface",
        "website": "https://huggingface.co/chat/",
        "apiWebsite": "https://huggingface.co/",
        "freeTier": True,
        "loginRequired": False,
        "authMode": "optional_login",
        "roles": ["code", "summary"],
    },
    {
        "id": "copilot",
        "name": "Microsoft Copilot",
        "provider": "microsoft",
        "website": "https://copilot.microsoft.com/",
        "apiWebsite": "https://ai.azure.com/",
        "freeTier": True,
        "loginRequired": False,
        "authMode": "optional_login",
        "roles": ["code", "summary", "translation"],
    },
    {
        "id": "mistral",
        "name": "Le Chat",
        "provider": "mistral",
        "website": "https://chat.mistral.ai/",
        "apiWebsite": "https://console.mistral.ai/",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["code", "review", "translation"],
    },
    {
        "id": "you",
        "name": "You.com",
        "provider": "you",
        "website": "https://you.com/",
        "apiWebsite": "https://api.you.com/",
        "freeTier": True,
        "loginRequired": False,
        "authMode": "optional_login",
        "roles": ["review", "summary"],
    },
    {
        "id": "phind",
        "name": "Phind",
        "provider": "phind",
        "website": "https://www.phind.com/",
        "apiWebsite": "",
        "freeTier": True,
        "loginRequired": False,
        "authMode": "optional_login",
        "roles": ["code", "review"],
    },
    {
        "id": "cerebras",
        "name": "Cerebras Chat",
        "provider": "cerebras",
        "website": "https://inference.cerebras.ai/",
        "apiWebsite": "https://inference.cerebras.ai/",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["code", "summary"],
    },
    {
        "id": "modelscope",
        "name": "ModelScope",
        "provider": "modelscope",
        "website": "https://modelscope.cn/",
        "apiWebsite": "https://modelscope.cn/",
        "freeTier": True,
        "loginRequired": True,
        "authMode": "web_login",
        "roles": ["code", "summary"],
    },
]


def list_ai_websites() -> list[dict]:
    return AI_WEBSITES


def get_ai_website(site_id: str) -> dict:
    for site in AI_WEBSITES:
        if site["id"] == site_id:
            return site
    raise KeyError(f"Unknown AI website: {site_id}")
