from __future__ import annotations

import json
import os
import time
import urllib.error
import urllib.request
from typing import Any

from backend.agents.base import BaseAgent
from backend.agents.mock_agent import MockAgent


class ClaudeAgent(BaseAgent):
    def __init__(
        self,
        name: str,
        provider: str,
        role: str,
        model: str,
        api_key_env_name: str,
        base_url: str = "https://api.anthropic.com",
        system_prompt: str = "",
        headers: dict[str, str] | None = None,
        extra_body: dict[str, Any] | None = None,
        model_mapping: dict[str, str] | None = None,
        timeout_seconds: int = 35,
        max_retries: int = 1,
    ) -> None:
        super().__init__(name=name, provider=provider, role=role)
        self.model = model
        self.api_key_env_name = api_key_env_name
        self.base_url = base_url.rstrip("/")
        self.system_prompt = system_prompt
        self.headers = headers or {}
        self.extra_body = extra_body or {}
        self.model_mapping = model_mapping or {}
        self.timeout_seconds = max(int(timeout_seconds), 5)
        self.max_retries = max(int(max_retries), 1)
        self._mock = MockAgent(name=name, provider="mock", role=role)

    def _api_key(self) -> str:
        return os.getenv(self.api_key_env_name, "").strip()

    def _request_message(self, prompt: str, context: dict[str, Any] | None = None, max_tokens: int = 500):
        api_key = self._api_key()
        if not api_key:
            return None, "missing_api_key", 0.0

        context = context or {}
        user_text = prompt
        if context.get("context_summary"):
            user_text = f"{user_text}\n\nContext:\n{context['context_summary']}"
        if context.get("shared_brief_summary"):
            user_text = f"{user_text}\n\nShared Brief:\n{context['shared_brief_summary']}"

        payload = {
            "model": self.model_mapping.get(self.model, self.model),
            "max_tokens": max_tokens,
            "system": self.system_prompt or "You are a helpful coding collaborator.",
            "messages": [{"role": "user", "content": user_text}],
        }
        payload.update(self.extra_body)
        request_headers = {
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        }
        request_headers.update(self.headers)
        request = urllib.request.Request(
            f"{self.base_url}/v1/messages",
            data=json.dumps(payload).encode("utf-8"),
            headers=request_headers,
            method="POST",
        )
        start = time.perf_counter()
        last_error = "unknown_error"
        for _ in range(self.max_retries):
            try:
                with urllib.request.urlopen(request, timeout=self.timeout_seconds) as response:
                    raw = response.read().decode("utf-8", errors="ignore")
                latency_ms = (time.perf_counter() - start) * 1000
                return json.loads(raw), None, latency_ms
            except urllib.error.URLError as exc:
                last_error = str(exc)
            except Exception as exc:  # noqa: BLE001
                last_error = str(exc)
        latency_ms = (time.perf_counter() - start) * 1000
        return None, last_error, latency_ms

    def _extract_text(self, data: dict[str, Any]) -> str:
        blocks = data.get("content", [])
        for block in blocks:
            if block.get("type") == "text":
                return str(block.get("text", "")).strip()
        return ""

    def call_model(self, prompt: str, context: dict[str, Any] | None = None) -> dict[str, Any]:
        data, error, _ = self._request_message(prompt, context=context)
        if error or not data:
            result = self._mock.call_model(prompt, context)
            result["fallback_to_mock"] = True
            result["provider_error"] = error or "unknown_error"
            return result
        content = self._extract_text(data)
        if not content:
            result = self._mock.call_model(prompt, context)
            result["fallback_to_mock"] = True
            result["provider_error"] = "empty_content"
            return result
        return {
            "claim": content[:600],
            "reasoning": "Generated by anthropic-compatible provider response.",
            "risks": ["Provider response should be validated against constraints."],
            "objections": [],
            "confidence": 0.75,
            "suggested_next_step": "Validate and convert to concrete implementation steps.",
            "fallback_to_mock": False,
        }

    def summarize_context(self, messages: list[dict]) -> dict:
        return self._mock.summarize_context(messages)

    def critique(self, shared_brief: dict) -> dict:
        prompt = "Critique the shared brief and propose the next best step."
        return self.call_model(prompt, {"shared_brief_summary": json.dumps(shared_brief)[:1400]})

    def vote(self, final_options: list[str]) -> dict:
        return self._mock.vote(final_options)

    def test_connection(self, prompt: str = "Respond with provider test ok") -> dict[str, Any]:
        data, error, latency_ms = self._request_message(prompt, max_tokens=30)
        if error or not data:
            return {"success": False, "fallback_to_mock": True, "error": error, "latency_ms": round(latency_ms, 2)}
        content = self._extract_text(data)
        return {
            "success": True,
            "fallback_to_mock": False,
            "latency_ms": round(latency_ms, 2),
            "preview": content[:120],
        }
