from __future__ import annotations

import json
import os
import time
import urllib.error
import urllib.request
from typing import Any

from backend.agents.base import BaseAgent
from backend.agents.mock_agent import MockAgent


class OpenAICompatibleAgent(BaseAgent):
    def __init__(
        self,
        name: str,
        provider: str,
        role: str,
        model: str,
        base_url: str,
        api_key_env_name: str,
        system_prompt: str = "",
        headers: dict[str, str] | None = None,
        extra_body: dict[str, Any] | None = None,
        model_mapping: dict[str, str] | None = None,
        timeout_seconds: int = 30,
        max_retries: int = 1,
    ) -> None:
        super().__init__(name=name, provider=provider, role=role)
        self.model = model
        self.base_url = base_url.rstrip("/")
        self.api_key_env_name = api_key_env_name
        self.system_prompt = system_prompt
        self.headers = headers or {}
        self.extra_body = extra_body or {}
        self.model_mapping = model_mapping or {}
        self.timeout_seconds = max(int(timeout_seconds), 5)
        self.max_retries = max(int(max_retries), 1)
        self._mock = MockAgent(name=name, provider="mock", role=role)

    def _api_key(self) -> str:
        return os.getenv(self.api_key_env_name, "").strip()

    def _build_messages(self, prompt: str, context: dict[str, Any] | None = None) -> list[dict[str, str]]:
        context = context or {}
        messages: list[dict[str, str]] = []
        if self.system_prompt:
            messages.append({"role": "system", "content": self.system_prompt})
        if context.get("context_summary"):
            messages.append({"role": "system", "content": f"Context summary: {context['context_summary']}"})
        if context.get("shared_brief_summary"):
            messages.append({"role": "system", "content": f"Shared brief: {context['shared_brief_summary']}"})
        messages.append({"role": "user", "content": prompt})
        return messages

    def _request_chat_completion(
        self,
        messages: list[dict[str, str]],
        temperature: float = 0.2,
        max_tokens: int = 600,
    ) -> tuple[dict[str, Any] | None, str | None, float]:
        api_key = self._api_key()
        if not api_key:
            return None, "missing_api_key", 0.0

        url = f"{self.base_url}/chat/completions"
        mapped_model = self.model_mapping.get(self.model, self.model)
        payload = {
            "model": mapped_model,
            "messages": messages,
            "temperature": temperature,
            "max_tokens": max_tokens,
        }
        payload.update(self.extra_body)
        body = json.dumps(payload).encode("utf-8")
        request_headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }
        request_headers.update(self.headers)
        request = urllib.request.Request(
            url,
            data=body,
            headers=request_headers,
            method="POST",
        )
        last_error = "unknown_error"
        start = time.perf_counter()
        for _ in range(self.max_retries):
            try:
                with urllib.request.urlopen(request, timeout=self.timeout_seconds) as response:
                    raw = response.read().decode("utf-8", errors="ignore")
                latency_ms = (time.perf_counter() - start) * 1000
                return json.loads(raw), None, latency_ms
            except urllib.error.URLError as exc:
                last_error = str(exc)
            except Exception as exc:  # noqa: BLE001
                last_error = str(exc)
        latency_ms = (time.perf_counter() - start) * 1000
        return None, last_error, latency_ms

    def call_model(self, prompt: str, context: dict[str, Any] | None = None) -> dict[str, Any]:
        messages = self._build_messages(prompt, context)
        data, error, _ = self._request_chat_completion(messages=messages)
        if error or not data:
            # Provider unavailable => graceful mock fallback.
            result = self._mock.call_model(prompt, context)
            result["fallback_to_mock"] = True
            result["provider_error"] = error or "unknown_error"
            return result

        content = (
            data.get("choices", [{}])[0]
            .get("message", {})
            .get("content", "")
            .strip()
        )
        if not content:
            result = self._mock.call_model(prompt, context)
            result["fallback_to_mock"] = True
            result["provider_error"] = "empty_content"
            return result

        return {
            "claim": content[:600],
            "reasoning": "Generated by openai-compatible provider response.",
            "risks": ["Provider response may require post-checking."],
            "objections": [],
            "confidence": 0.73,
            "suggested_next_step": "Validate generated answer against project constraints.",
            "fallback_to_mock": False,
        }

    def summarize_context(self, messages: list[dict[str, Any]]) -> dict[str, Any]:
        return self._mock.summarize_context(messages)

    def critique(self, shared_brief: dict[str, Any]) -> dict[str, Any]:
        prompt = (
            "Critique the current shared brief and provide a refined claim, reasoning, risks, objections, and suggested_next_step."
        )
        return self.call_model(prompt, {"shared_brief_summary": json.dumps(shared_brief)[:1400]})

    def vote(self, final_options: list[str]) -> dict[str, Any]:
        return self._mock.vote(final_options)

    def test_connection(self, prompt: str = "Respond with provider test ok") -> dict[str, Any]:
        messages = self._build_messages(prompt)
        data, error, latency_ms = self._request_chat_completion(messages=messages, max_tokens=20)
        if error or not data:
            return {"success": False, "fallback_to_mock": True, "error": error, "latency_ms": round(latency_ms, 2)}
        content = data.get("choices", [{}])[0].get("message", {}).get("content", "")
        return {
            "success": True,
            "fallback_to_mock": False,
            "latency_ms": round(latency_ms, 2),
            "preview": str(content)[:120],
        }
